spring:
  application:
    name: malrota-backend

  config:
    import: optional:file:.env[.properties]


server:
  port: ${PORT:8081}

malrota:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  integrations:
    tago:
      enabled: ${TAGO_ENABLED:false}
      service-key: ${TAGO_SERVICE_KEY:}

    watsonx:
      enabled: ${WATSONX_ENABLED:false}
      api-key: ${WATSONX_API_KEY:}
      project-id: ${WATSONX_PROJECT_ID:}
      url: ${WATSONX_URL:}

    speech:
      stt-enabled: ${IBM_STT_ENABLED:false}
      stt-api-key: ${IBM_STT_API_KEY:}
      stt-url: ${IBM_STT_URL:}
      
      tts-enabled: ${IBM_TTS_ENABLED:false}
      tts-api-key: ${IBM_TTS_API_KEY:}
      tts-url: ${IBM_TTS_URL:}
